# Generated by Django 4.2.5 on 2023-09-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mememo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="env",
            field=models.JSONField(default=dict),
        ),
    ]
