# Generated by Django 4.2.5 on 2023-09-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mememo", "0003_thirdpartyauthentication"),
    ]

    operations = [
        migrations.CreateModel(
            name="MememoPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    (
                        "third_party_gateway",
                        "User can act as a third-party authentication gateway.",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
